// <auto-generated />
namespace Tridion.Snitch.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SnitchDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SnitchDb));
        
        string IMigrationMetadata.Id
        {
            get { return "201606080817565_SnitchDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
